(function(){
'use strict';
const BOOK_URL='https://dragolaida-casas-v7.vercel.app/api/book1';
const K_BOOK='dragolaida.book1.v10', K_CH='dragolaida.chapter.v10', K_QUEUE='dragolaida.messages.v10', K_REW='dragolaida.rewards.v10';
let book=null, chapter=0, installPrompt=null, ttsToken=0, chunks=[], chunkIndex=0, keepAlive=null;
const $=id=>document.getElementById(id);
function toast(msg,ms=2800){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),ms)}
function getJSON(k,fallback){try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}}
function setJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function loadLocalBook(){const b=getJSON(K_BOOK,null); if(b&&Array.isArray(b.chapters)&&b.chapters.length){book=b;return true} return false}
async function prepareBook(show=true){
  if(loadLocalBook()){readyUI(); if(!navigator.onLine){if(show)toast('✓ Libro I ya está disponible sin conexión.');return true}}
  if(!navigator.onLine){if(show)toast('Conéctate una vez para preparar el Libro I.');return !!book}
  try{
    const r=await fetch(BOOK_URL,{cache:'no-store',mode:'cors'}); if(!r.ok)throw new Error('HTTP '+r.status);
    const b=await r.json(); if(!b||!Array.isArray(b.chapters)||b.chapters.length!==26)throw new Error('Libro incompleto');
    if(!setJSON(K_BOOK,b))throw new Error('No pude guardar el libro'); book=b; readyUI();
    if(show)toast('✓ Libro I guardado. Ya puede leerse sin Internet.'); return true;
  }catch(err){ if(loadLocalBook()){readyUI(); if(show)toast('Usando la copia local del Libro I.'); return true} if(show)toast('No pude preparar el Libro I: '+err.message,4200); return false }
}
function readyUI(){const b=$('readyBadge'); if(b)b.classList.add('show')}
function showScreen(id){['home','reader','library','family','bemba','exam'].forEach(x=>$(x).classList.toggle('active',x===id));$('bottom').hidden=(id==='home'||id==='bemba');window.scrollTo(0,0); if(id==='library')renderLibrary(); if(id==='bemba')renderRewards(); if(id==='family')renderQueue();}
function ensureBook(){if(book&&book.chapters&&book.chapters.length)return true;if(loadLocalBook()){readyUI();return true}toast('Toca PREPARAR / ACTUALIZAR una vez con Internet.');return false}
function openReader(autoSpeak=false){if(!ensureBook())return;chapter=DragonCore.clampChapter(localStorage.getItem(K_CH)||0,book.chapters.length);renderReader();showScreen('reader');if(autoSpeak)setTimeout(startNarration,120)}
function renderReader(){if(!ensureBook())return;chapter=DragonCore.clampChapter(chapter,book.chapters.length);localStorage.setItem(K_CH,String(chapter));const ch=book.chapters[chapter];$('readerMeta').textContent='Libro I · Capítulo '+(chapter+1)+' de '+book.chapters.length;$('readerTitle').textContent=ch.title||('Capítulo '+(chapter+1));$('readerText').textContent=ch.text||'';$('readerProgress').style.width=Math.round((chapter+1)/book.chapters.length*100)+'%';}
function nextChapter(){stopNarration(false);if(!ensureBook())return;if(chapter<book.chapters.length-1){chapter++;renderReader();awardProgress()}else{toast('🐾 BEMBA: ¡Libro I terminado! Vamos al examen.');localStorage.setItem('dragolaida.finished.v10','1');setTimeout(renderExam,550)}}
function prevChapter(){stopNarration(false);if(chapter>0)chapter--;renderReader()}
function renderLibrary(){const el=$('libraryList');if(!el)return;const first=book?`<div class="bookrow"><div class="cover">LIBRO I</div><div><b>${book.display_title||book.title}</b><div class="small">26 capítulos · disponible offline</div></div><button class="ctl" data-action="read">ABRIR</button></div>`:`<p>Prepara el Libro I para comenzar.</p>`;const locked=Array.from({length:7},(_,i)=>`<div class="bookrow lock"><div class="cover">🔒 ${i+2}</div><div><b>Libro ${i+2}</b><div class="small">Esperando autorización de DRACOXIEL</div></div><span>🔒</span></div>`).join('');el.innerHTML=first+locked;}
function voices(){return ('speechSynthesis'in window)?speechSynthesis.getVoices():[]}
function pickVoice(){const vs=voices();return vs.find(v=>/^es/i.test(v.lang)&&v.localService)||vs.find(v=>/^es/i.test(v.lang))||vs.find(v=>v.localService)||vs[0]||null}
function voiceSupported(){return 'speechSynthesis'in window && 'SpeechSynthesisUtterance'in window}
function updateVoiceUI(msg,detail){if($('voiceState'))$('voiceState').textContent=msg;if($('voiceDetail'))$('voiceDetail').textContent=detail||''}
function speakPart(token){if(token!==ttsToken||chunkIndex>=chunks.length){updateVoiceUI('✓ Narración finalizada','Puedes continuar al capítulo siguiente.');clearInterval(keepAlive);keepAlive=null;return}const u=new SpeechSynthesisUtterance(chunks[chunkIndex]);const v=pickVoice();if(v)u.voice=v;u.lang=(v&&v.lang)||'es-ES';u.rate=.88;u.pitch=1;u.volume=1;u.onstart=()=>updateVoiceUI('🔊 Narrando '+(chunkIndex+1)+'/'+chunks.length,v?('Voz: '+v.name+' · '+v.lang):'Voz predeterminada del teléfono');u.onend=()=>{if(token!==ttsToken)return;chunkIndex++;setTimeout(()=>speakPart(token),40)};u.onerror=e=>updateVoiceUI('⚠ Error de voz','TTS: '+(e.error||'sin respuesta'));speechSynthesis.speak(u)}
function startNarration(){if(!ensureBook())return;if(!voiceSupported()){updateVoiceUI('✕ TTS no disponible','Este navegador no expone el narrador del teléfono.');toast('La voz no está disponible en este navegador.');return}if(!$('reader').classList.contains('active')){chapter=DragonCore.clampChapter(localStorage.getItem(K_CH)||0,book.chapters.length);renderReader();showScreen('reader')}stopNarration(false);chunks=DragonCore.chunkText(book.chapters[chapter].text,135);chunkIndex=0;ttsToken++;const token=ttsToken;updateVoiceUI('Preparando narración…','Fragmentos cortos para mayor compatibilidad con Android.');setTimeout(()=>speakPart(token),120);keepAlive=setInterval(()=>{try{if(speechSynthesis.speaking&&!speechSynthesis.paused)speechSynthesis.resume()}catch{}},9000)}
function testVoice(){if(!voiceSupported()){toast('TTS no disponible en este navegador.');return}stopNarration(false);chunks=['Hola. Soy Dragolaida. Si escuchas esto, la voz del teléfono está funcionando.'];chunkIndex=0;ttsToken++;const token=ttsToken;updateVoiceUI('Probando voz…','');setTimeout(()=>speakPart(token),120)}
function pauseNarration(){if(!voiceSupported())return;if(speechSynthesis.paused){speechSynthesis.resume();updateVoiceUI('🔊 Narrando','Narración reanudada.')}else if(speechSynthesis.speaking){speechSynthesis.pause();updateVoiceUI('⏸ Narración en pausa','Toca Pausa otra vez para continuar.')}else startNarration()}
function stopNarration(show=true){ttsToken++;if(keepAlive){clearInterval(keepAlive);keepAlive=null}try{if(voiceSupported())speechSynthesis.cancel()}catch{}if(show)updateVoiceUI('Narrador detenido','Toca Escuchar para comenzar.')}
function getRewards(){return Object.assign({bones:0,skins:0,tails:0},getJSON(K_REW,{}))}
function saveRewards(r){setJSON(K_REW,r);renderRewards()}
function awardProgress(){const last=Number(localStorage.getItem('dragolaida.rewarded.chapter.v10')||-1);if(chapter<=last)return;let r=getRewards();r=DragonCore.addReward(r,'bone');if((chapter+1)%3===0)r=DragonCore.addReward(r,'skin');if((chapter+1)%7===0)r=DragonCore.addReward(r,'tail');saveRewards(r);localStorage.setItem('dragolaida.rewarded.chapter.v10',String(chapter));toast('🦴 BEMBA te dejó una recompensa por seguir leyendo.')}
function renderRewards(){const r=getRewards();if($('bonesCount'))$('bonesCount').textContent=r.bones;if($('skinsCount'))$('skinsCount').textContent=r.skins;if($('tailsCount'))$('tailsCount').textContent=r.tails}
function catchReward(){let r=getRewards();const n=Math.random();const type=n<.68?'bone':n<.92?'skin':'tail';r=DragonCore.addReward(r,type);saveRewards(r);const label=type==='bone'?'🦴 Huesito':type==='skin'?'🍗 Pellejo':'🐔 Culito de pollo';toast(label+' atrapado. ¡La gallina protesta! 🐔')}
function getQueue(){return getJSON(K_QUEUE,[])}
function saveQueue(q){setJSON(K_QUEUE,q);renderQueue()}
function renderQueue(){const el=$('messageQueue');if(!el)return;const q=getQueue();el.innerHTML=q.length?q.slice().reverse().map(m=>`<div class="queued"><div>${escapeHtml(m.text)}</div><span class="pill">${m.status}</span></div>`).join(''):'<div class="small">No hay mensajes pendientes.</div>'}
function sendMessage(){const box=$('familyMessage');const text=box.value.trim();if(!text)return toast('Escribe un mensaje primero.');let q=DragonCore.enqueueMessage(getQueue(),text);saveQueue(q);box.value='';if(navigator.onLine){const last=q[q.length-1];last.status='ABRIENDO CORREO';saveQueue(q);location.href='mailto:axieldiazcasasam@desaplicaxi.com?subject='+encodeURIComponent('DRAGONZZAP · DRAGOLAIDA')+'&body='+encodeURIComponent(text)}else toast('Mensaje guardado como PENDIENTE. Se conserva sin conexión.')}
function retryMessages(){const q=getQueue();const m=q.find(x=>x.status==='PENDIENTE');if(!m)return toast('No hay mensajes pendientes.');if(!navigator.onLine)return toast('Sigue sin Internet; el mensaje permanece guardado.');m.status='ABRIENDO CORREO';saveQueue(q);location.href='mailto:axieldiazcasasam@desaplicaxi.com?subject='+encodeURIComponent('DRAGONZZAP · DRAGOLAIDA')+'&body='+encodeURIComponent(m.text)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderExam(){showScreen('exam');const questions=[['¿Qué fenómeno inicia el Libro I?',['El agua asciende','Una torre cae','Un dragón desaparece'],0],['¿Cómo se llama la escritura relacional?',['Rha Shem','Ráhum Azul','Nhar-Sael'],0],['¿Qué aprende Karyss sobre no saber?',['Que no saber puede ser provisional','Que siempre debe adivinar','Que debe ocultarlo'],0],['¿Qué condición descubre sobre proteger?',['Proteger debe conservar salida','Proteger exige encerrar','Proteger significa obedecer'],0],['¿Cómo termina el libro?',['Con equilibrio provisional, no una victoria total','Con la destrucción de Saelvara','Con el fin de las doce Tierras'],0]];let html='<p>Responde las 5 preguntas sobre tu lectura.</p>';questions.forEach((q,i)=>{html+=`<div class="exam-q"><b>${i+1}. ${q[0]}</b>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`});html+='<button class="ctl primary" type="submit">CORREGIR TEST</button><div id="examResult" class="exam-result"></div>';$('examForm').innerHTML=html;$('examForm').onsubmit=e=>{e.preventDefault();let score=0;questions.forEach((q,i)=>{const v=$('examForm').querySelector(`input[name=q${i}]:checked`);if(v&&Number(v.value)===q[2])score++});$('examResult').textContent=`Resultado: ${score}/5`;localStorage.setItem('dragolaida.exam.v10',String(score));toast(score>=4?'🐾 BEMBA está muy contenta.':'BEMBA dice que puedes volver a intentarlo.')}}
function handle(action){switch(action){case'install':doInstall();break;case'read':openReader(false);break;case'listen':openReader(true);break;case'family':showScreen('family');break;case'bemba':showScreen('bemba');renderRewards();break;case'prepare':prepareBook(true);break;case'home':stopNarration(false);showScreen('home');break;case'library':showScreen('library');break;case'prev':prevChapter();break;case'next':nextChapter();break;case'speak':startNarration();break;case'pause':pauseNarration();break;case'stop':stopNarration(true);break;case'test-voice':testVoice();break;case'catch-reward':catchReward();break;case'send-message':sendMessage();break;case'retry-messages':retryMessages();break}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){e.preventDefault();handle(b.dataset.action)}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
async function doInstall(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('Chrome ⋮ → Instalar aplicación / Añadir a pantalla principal.')}
function onlineUI(){ $('offline').classList.toggle('show',!navigator.onLine) }
window.addEventListener('online',()=>{onlineUI();prepareBook(false)});window.addEventListener('offline',onlineUI);
window.addEventListener('load',async()=>{onlineUI();loadLocalBook();if(book)readyUI();renderRewards();if('serviceWorker'in navigator){try{const r=await navigator.serviceWorker.register('./sw.js?v=10g');await r.update();if(r.waiting)r.waiting.postMessage('SKIP_WAITING')}catch(e){console.warn(e)}}await prepareBook(false);if(voiceSupported()){try{speechSynthesis.onvoiceschanged=()=>{};speechSynthesis.getVoices()}catch{}}});
})();
